### ISSUE TITLE
Mdl to Vmdl

### ISSUE THREAD

**Issue by mancubminecraft** [Rectus/source2utils#1]
Will there ever be a mdl to vmdl converter?

**Comment by Rectus** [comment]
The engine seems to have some kind of support for this already:
[https://developer.valvesoftware.com/wiki/Half-Life:_Alyx_Workshop_Tools/Importing_Source_1_Models](https://developer.valvesoftware.com/wiki/Half-Life:_Alyx_Workshop_Tools/Importing_Source_1_Models)
